name: svelte-hamburgers Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
            version: 8.6.1

      - run: pnpm i
      - run: pnpm package

      - run: |
          pnpm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          pnpm publish --no-git-checks
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
